name: Build and deploy GH Pages
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Use the automatic token for same repo deployment
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Specify the project name in the base_url
          BUILD_DIR: .
          BUILD_ONLY: false
          BUILD_FLAGS: --base-url="https://qianzehao123.github.io/zehao.qian.home"